apiVersion: v1
kind: Service
metadata:
  name: api-managment-service
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer for external access
  selector:
    app: api-managment
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
