apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-front
  template:
    metadata:
      labels:
        app: my-front
    spec:
      containers:
        - name: my-front
          image: my-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
