apiVersion: v1
kind: Service
metadata:
  name: my-front-service
spec:
  type: NodePort
  selector:
    app: my-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
