apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-backend
  template:
    metadata:
      labels:
        app: customer-backend
    spec:
      containers:
      - name: customer-backend
        image: customer-backend:latest  # Replace with your Docker image name
        imagePullPolicy: Always
        ports:
        - containerPort: 6555
