apiVersion: v1
kind: Service
metadata:
  name: customer-backend-service
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer for external access
  selector:
    app: customer-backend
  ports:
    - protocol: TCP
      port: 6555
      targetPort: 6555
